name: QA

on: 
  pull_request:
    branches:
      - master

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run GolangCI-Lint Action by pulling pre-built image
        uses: docker://matoous/golangci-lint-action:v1.1.0
